### ISSUE TITLE
Size of mainPanel/dashboardBody

### ISSUE THREAD

**Issue by mlieberwu** [sru-wu/matflow_visual_2.0#5]
Currently the chart doesn't use the full height of the dashboardBody. 

The following solutions have not worked out:

- Setting heights and widths at different points in the code
- Using fillPage (https://shiny.rstudio.com/reference/shiny/1.0.5/fillPage.html)

**Comment by krsriq** [comment]
Fixed for modern browsers (tested in Chrome, FF)
